[package]
name = "dice-spec-perf"
version = "0.1.0"
authors = ["J/A <jarcher@balglobal.com>"]
edition = "2018"

[dependencies]
pest = "2.0"
pest_derive = "2.0"
regex = "1.0"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "specifications"
harness = false
